### USERS
GET http://127.0.0.1/api/users/1/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
POST http://127.0.0.1/api/users/ HTTP/1.1   
content-type: application/json

{
  "email": "vpupkifn@yandex.ru",
  "username": "mfee",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "password": "13124aj124fgb;adjfbgadf22"
}
###
POST http://127.0.0.1/api/auth/token/login/ HTTP/1.1
content-type: application/json

{
  "email": "vpupkin@yandex.ru",
  "password": "13124aj124fgb;adjfbgadf22"
}
###
POST http://127.0.0.1/api/auth/token/logout/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
POST http://127.0.0.1/api/users/set_password/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c

{
  "new_password": "13124aj124fgb;adjfbgadf",
  "current_password": "13124aj124fgb;adjfbgadf2"
}
###
### SUBSCRIPES
GET http://127.0.0.1/api/users/subscriptions/?recipes_limit=2 HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
POST http://127.0.0.1/api/users/1/subscribe/?recipes_limit=2 HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
DELETE http://127.0.0.1/api/users/1/subscribe/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
# 
# Authorization: Token b5be6520de6677bbc969587649855211306a447c
# 
# 
### TAGS
GET http://127.0.0.1/api/tags/ HTTP/1.1
###
#
# ?page=1&limit=999&is_in_shopping_cart=1
#
#
### RECIPES
GET http://127.0.0.1/api/recipes/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
DELETE http://127.0.0.1/api/recipes/4/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
PATCH http://127.0.0.1/api/recipes/11/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c

{
    "name": "Макароны по-флотски",
    "text": "в",
    "cooking_time": 5,
    "ingredients": [
        {
            "id": 2,
            "amount": 12
        },
        {
            "id": 1,
            "amount": 12
        }
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "tags": [
        2
    ]
}
###
POST http://127.0.0.1/api/recipes/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c

{
    "ingredients": [
        {
            "id": 2,
            "amount": 1
        },
        {
            "id": 1,
            "amount": 13
        }
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "tags": [
        1
    ],
    "name": "Рыба в соусе",
    "text": "в2",
    "cooking_time": 1
}
###
### FAVORITE
POST http://127.0.0.1/api/recipes/3/favorite/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
DELETE  http://127.0.0.1/api/recipes/3/favorite/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
### SHOPPING_CART
POST http://127.0.0.1/api/recipes/3/shopping_cart/ HTTP/1.1
content-type: application/json
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
DELETE http://127.0.0.1/api/recipes/3/shopping_cart/ HTTP/1.1
Authorization: Token b5be6520de6677bbc969587649855211306a447c
###
#
# 
#
#
### INGRIDIENTS
GET http://127.0.0.1/api/ingredients/ HTTP/1.1